- name: Include uninstall tasks if requested
  ansible.builtin.include_tasks: uninstall.yml
  when: uninstall_k3s | default(false)

- name: Include worker node install tasks
  ansible.builtin.include_tasks: install.yml
  when: not uninstall_k3s | default(false)
