- hosts: all
  tasks:
  
  - name: Uninstall Control k3s
    become: yes
    command: /usr/local/bin/k3s-uninstall.sh
    when: inventory_hostname in groups['main_control'] or inventory_hostname in groups['control']

  - name: Uninstall k3s Workers
    become: yes
    command: /usr/local/bin/k3s-agent-uninstall.sh 
    when: inventory_hostname in groups['workers']
