- hosts: all

  tasks:
  - name: Uninstall Control k3s
    become: yes
    command: /usr/local/bin/k3s-uninstall.sh
    when: inventory_hostname in groups['main_control'] or inventory_hostname in groups['control'] 
