- name: Check if K3s uninstall script exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_uninstall_script

- name: Uninstall control nodes
  become: true
  ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
  when: k3s_uninstall_script.stat.exists
