- name: Add Rancher Helm repository
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable

- name: Install Rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    chart_version: "{{ rancher_ver }}"
    release_namespace: cattle-system
    state: present
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 30m0s
    values:
      hostname: "{{ rancher_fqdn }}"
      replicas: "{{ rancher_n_replicas }}"
