- name: Uninstall Rancher Helm release
  kubernetes.core.helm:
    name: rancher
    release_namespace: cattle-system
    state: absent

- name: Remove Rancher Helm repository
  kubernetes.core.helm_repository:
    name: rancher-stable
    state: absent
