- name: Install Cert Manager CRDs
  ansible.builtin.shell: |
    kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/download/v{{ cert_manager_ver }}/cert-manager.crds.yaml
  register: apply_result
  changed_when: "'configured' not in apply_result.stdout and 'unchanged' not in apply_result.stdout"

- name: Add Jetstack Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install Cert Manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "v{{ cert_manager_ver }}"
    release_namespace: cert-manager
    state: present
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 15m0s
    atomic: true
