- name: Setup Load Balancer for Control Nodes
  hosts: control_load_balancer
  become: true
  roles:
    - role: control_lb

- name: Setup K3s Main Control Node
  hosts: main_control
  become: true
  roles:
    - role: main_control

- name: Setup K3s Control Nodes
  hosts: control_nodes
  become: true
  roles:
    - role: control_node

- name: Setup K3s Worker Nodes
  hosts: worker_nodes
  become: true
  roles:
    - role: worker_node

- name: Setup MetalLB load balancer
  hosts: main_control
  become: true
  roles:
    - role: metallb

- name: Prepare local dev machine for k3s management
  hosts: localhost
  roles:
    - role: dev_machine
      vars:
        control_host: "{{ groups['main_control'][0] }}"
        remote_kubeconfig: "/etc/rancher/k3s/k3s.yaml"

- name: Install Cert-Manager
  hosts: localhost
  connection: local
  roles:
    - role: cert_manager

- name: Install Rancher
  hosts: localhost
  connection: local
  roles:
    - role: rancher
