- name: Setup Load Balancer for Control Nodes
  hosts: control_load_balancer
  become: true
  roles:
    - role: control_lb

- name: Setup K3s Main Control Node
  hosts: main_control
  become: true
  roles:
    - role: main_control

- name: Setup K3s Control Nodes
  hosts: control_nodes
  become: true
  roles:
    - role: control_node

- name: Setup K3s Worker Nodes
  hosts: worker_nodes
  become: true
  roles:
    - role: worker_node

- name: Setup MetalLB load balancer
  hosts: main_control
  become: true
  roles:
    - role: metallb

- name: Install Rancher
  hosts: main_control
  become: true
  roles:
    - role: rancher
