- name: Prepare local dev machine for k3s management
  hosts: localhost
  roles:
    - role: dev_machine
      vars:
        control_host: "{{ groups['main_control'][0] }}"
        remote_kubeconfig: "/etc/rancher/k3s/k3s.yaml"

- name: Uninstall Rancher
  hosts: localhost
  connection: local
  roles:
    - role: rancher

- name: Remove MetalLB load balancer
  hosts: main_control
  become: true
  roles:
    - role: metallb

- name: Wind down K3s Worker Nodes
  hosts: worker_nodes
  become: true
  roles:
    - role: worker_node

- name: Wind down K3s Control Nodes
  hosts: control_nodes
  become: true
  roles:
    - role: control_node

- name: Wind down K3s Main Control Node
  hosts: main_control
  become: true
  roles:
    - role: main_control

- name: Uninstall Load Balancer for Control Nodes
  hosts: control_load_balancer
  become: true
  roles:
    - role: control_lb
