# metallb-conf.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168-192.168
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-adv-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool