apiVersion: v1
kind: Service
metadata:
  name: rancher-cip
  namespace: cattle-system
  annotations:
    field.cattle.io/description: Cluster IP to Rancher's UI HTTP
spec:
  type: ClusterIP
  selector:
    app: rancher
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
