- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install the main control node (ETCD)
  ansible.builtin.shell: |
    /tmp/k3s-install.sh
  args:
    creates: /etc/systemd/system/k3s.service
  environment:
    INSTALL_K3S_CHANNEL: "v{{ k3s_ver }}"
    INSTALL_K3S_EXEC: "server --disable servicelb --cluster-init --write-kubeconfig-mode 644 --tls-san {{ control_lb_virtual_ip }}"
    K3S_KUBECONFIG_MODE: "644"
