- name: Include k3s uninstall tasks if requested
  ansible.builtin.include_tasks: uninstall_k3s.yml
  when: uninstall_k3s | default(false)

- name: Include etcd install tasks
  ansible.builtin.include_tasks: install_with_etcd.yml
  when:
    - not uninstall_k3s | default(false)
    - k3s_datastore == "ETCD"

- name: Include DB drop tasks
  ansible.builtin.include_tasks: drop_db.yml
  when:
    - uninstall_k3s | default(false)
    - k3s_datastore == "EDB"

- name: Include external DB install tasks
  ansible.builtin.include_tasks: install_with_mysql.yml
  when:
    - not uninstall_k3s | default(false)
    - k3s_datastore == "EDB"

- name: Include Traefik's setup tasks
  ansible.builtin.include_tasks: setup_traefik.yml
  when: not uninstall_k3s | default(false)

- name: Include get token tasks
  ansible.builtin.include_tasks: get_token.yml
  when: not uninstall_k3s | default(false)
