- name: Check if K3s uninstall script exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_uninstall_script

- name: Uninstall the main control node
  become: true
  ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
  when: k3s_uninstall_script.stat.exists

- name: Drop the MySQL database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: absent
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_pass }}"
  delegate_to: localhost
  run_once: true
  become: false
