- name: Stop HAProxy
  ansible.builtin.service:
    name: haproxy
    state: stopped
    enabled: false
  become: true

- name: Stop Keepalived
  ansible.builtin.service:
    name: keepalived
    state: stopped
    enabled: false
  become: true

- name: Uninstall HAProxy and Keepalived
  ansible.builtin.apt:
    name:
      - haproxy
      - keepalived
    state: absent
    purge: true
  become: true

- name: Remove HAProxy config
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg
    state: absent
  become: true

- name: Remove Keepalived config
  ansible.builtin.file:
    path: /etc/keepalived/keepalived.conf
    state: absent
  become: true
