- name: Check if kubectl is available
  ansible.builtin.command: which kubectl
  register: kubectl_check
  ignore_errors: true

- name: Delete MetalLB configuration
  ansible.builtin.shell: |
    kubectl delete -k /tmp/metallb-kustomization/metallb-conf.yaml
  register: delete_metallb
  changed_when: "'deleted' in delete_metallb.stdout"
  failed_when: delete_metallb.rc != 0 and 'NotFound' not in delete_metallb.stdout
  when: kubectl_check.rc == 0

- name: Delete MetalLB manifest
  ansible.builtin.shell: |
    kubectl delete -k /tmp/metallb-kustomization
  register: delete_metallb
  changed_when: "'deleted' in delete_metallb.stdout"
  failed_when: delete_metallb.rc != 0 and 'NotFound' not in delete_metallb.stdout
  when: kubectl_check.rc == 0

- name: Delete metallb-kustomization directory
  ansible.builtin.file:
    path: /tmp/metallb-kustomization
    state: absent
